name: (📡) Verify

on:
  push:
    branches-ignore:
      - 'main'
      - "support/*"
  workflow_dispatch:

jobs:
  verify:
    uses: sitepark/github-project-workflow/.github/workflows/maven-verify.yml@release/1.x

